TYPO3:
  FormBuilder:
    newFormTemplates:
      'resource://TYPO3.FormBuilder/Private/NewFormTemplates/Blank.yaml': Blank

    javaScripts:
      jQuery:
        sorting: 10
        files: ['resource://TYPO3.FormBuilder/Public/Library/jquery-1.7.1.min.js', 'resource://TYPO3.FormBuilder/Public/Library/jquery-ui.min.js']
      jQueryLayout:
        sorting: 15
        files: ['resource://TYPO3.FormBuilder/Public/Library/jquery.layout.js']
      ember:
        sorting: 20
        files: ['resource://TYPO3.FormBuilder/Public/Library/ember-0.9.4.js']
      dynatree:
        sorting: 25
        files: ['resource://TYPO3.FormBuilder/Public/Library/dynatree-1.2.0/src/jquery.dynatree.js']
      slickGrid:
        sorting: 30
        files:
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/lib/jquery.event.drag-2.0.min.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/slick.core.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/plugins/slick.cellrangedecorator.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/plugins/slick.cellrangeselector.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/plugins/slick.cellselectionmodel.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/plugins/slick.rowselectionmodel.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/plugins/slick.rowmovemanager.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/slick.editors.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/slick.grid.js'
      application:
        files: ['resource://TYPO3.FormBuilder/Public/JavaScript/app.js']
        sorting: 100

    stylesheets:
      slickGrid:
        sorting: 10
        files: ['resource://TYPO3.FormBuilder/Public/Library/SlickGrid/slick.grid.wrapped.css']
      application:
        sorting: 100
        files: ['resource://TYPO3.FormBuilder/Public/Css/FormBuilder.css']

    handlebarsTemplates:
      # Main application layout
      Application: resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/Application.html
      Header: resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/Header.html
      StructurePanel: resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/StructurePanel.html
      InsertElementsPanel: resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/InsertElementsPanel.html

      # Element options panel parts
      ElementOptionsPanel-FinisherEditor:  resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/ElementOptionsPanel/FinisherEditor.html
      ElementOptionsPanel-IdentifierEditor:  resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/ElementOptionsPanel/IdentifierEditor.html
      ElementOptionsPanel-PropertyGridEditor:  resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/ElementOptionsPanel/PropertyGridEditor.html
      ElementOptionsPanel-PropertyPanelTitle:  resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/ElementOptionsPanel/PropertyPanelTitle.html
      ElementOptionsPanel-RemoveElement:  resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/ElementOptionsPanel/RemoveElement.html
      ElementOptionsPanel-RequiredValidatorEditor:  resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/ElementOptionsPanel/RequiredValidatorEditor.html
      ElementOptionsPanel-TextEditor:  resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/ElementOptionsPanel/TextEditor.html
      ElementOptionsPanel-TextareaEditor:  resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/ElementOptionsPanel/TextareaEditor.html
      ElementOptionsPanel-SelectEditor:  resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/ElementOptionsPanel/SelectEditor.html
      ElementOptionsPanel-ValidatorEditor:  resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/ElementOptionsPanel/ValidatorEditor.html

      # Validator Editors
      Validator-Default: resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/Validator/Default.html
      Validator-MinimumMaximumEditor: resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/Validator/MinimumMaximumEditor.html
      Validator-SimpleValueEditor: resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/Validator/SimpleValueEditor.html

      # Finisher Editors
      Finisher-EmailEditor: resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/Finisher/EmailEditor.html
      Finisher-RedirectEditor: resource://TYPO3.FormBuilder/Private/FormBuilderTemplates/Finisher/RedirectEditor.html

  Form:
    supertypeResolver:
      hiddenProperties:
        formBuilder: formBuilder
    presets:
      ########### DEFAULT ###########
      default:
        validatorPresets:
          'TYPO3.FormBuilder:ZipCode':
            implementationClassName: 'TYPO3\FLOW3\Validation\Validator\RegularExpressionValidator'
            options:
              regularExpression: '/^[0-9]{5}$/'

        formElementGroups:
          input:
            sorting: 100
            label: 'Input Form Elements'
          select:
            sorting: 200
            label: 'Select Form Elements'
          custom:
            sorting: 300
            label: 'Custom Form Elements'
          container:
            sorting: 400
            label: 'Container Form Elements'

        formElementTypes:
          'TYPO3.Form:Base':
            formBuilder:
              editors:
                elementType:
                  sorting: 100
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.TextOutput'
                  templateName: 'ElementOptionsPanel-PropertyPanelTitle'
          'TYPO3.Form:ReadOnlyFormElement':
            formBuilder:
              editors:
                label:
                  label: 'Title'
                  propertyPath: 'label'
                  sorting: 120
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.TextEditor'
          'TYPO3.Form:FormElement':
            formBuilder:
              editors:
                identifier:
                  sorting: 110
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.IdentifierEditor'
                label:
                  label: 'Label'
                  propertyPath: 'label'
                  sorting: 120
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.TextEditor'
                requiredValidator:
                  sorting: 800
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.RequiredValidatorEditor'

                validation:
                  sorting: 900
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.ValidatorEditor'

          'TYPO3.Form:Form':
            formBuilder:
              label: 'Form'
              _isCompositeRenderable: false
              _isTopLevel: true
              editors:
                identifier:
                  sorting: 110
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.IdentifierEditor'
                label:
                  label: 'Form Name'
                  propertyPath: 'label'
                  sorting: 120
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.TextEditor'
                submitButtonLabel:
                  sorting: 200
                  label: 'Submit Label'
                  propertyPath: 'renderingOptions.submitButtonLabel'
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.TextEditor'

                finishers:
                  sorting: 410
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.FinisherEditor'
                  availableFinishers:
                    'TYPO3.Form:Email':
                      label: 'Send Email'
                      viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.FinisherEditor.EmailFinisherEditor'
                      availableFormats:
                        0: {key: 'plaintext', value: 'Plain Text'}
                        1: {key: 'html', value: 'HTML'}
                    'TYPO3.Form:Redirect':
                      label: 'Redirect to controller/action'
                      templateName: 'Finisher-RedirectEditor'


          'TYPO3.Form:RemovableMixin':
            formBuilder:
              editors:
                removeButton:
                  sorting: 999
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.RemoveElementEditor'

          # group INPUT
          'TYPO3.Form:SingleLineText':
            formBuilder:
              label: 'Single-Line Text'
              group: input
              sorting: 100

          'TYPO3.Form:MultiLineText':
            formBuilder:
              label: 'Multi-Line Text'
              group: input
              sorting: 110

          'TYPO3.Form:Password':
            formBuilder:
              label: 'Password field'
              group: input
              sorting: 120

          # group SELECT
          'TYPO3.Form:Checkbox':
            formBuilder:
              label: 'Single Checkbox'
              group: select
              sorting: 100

          'TYPO3.Form:SingleSelectDropdown':
            formBuilder:
              label: 'Single Select (Dropdown)'
              group: select
              sorting: 110

          'TYPO3.Form:SingleSelectRadiobuttons':
            formBuilder:
              label: 'Single Select (Radiobuttons)'
              group: select
              sorting: 120

          'TYPO3.Form:MultipleSelectDropdown':
            formBuilder:
              label: 'Multiple Select (Dropdown)'
              group: select
              sorting: 130

          'TYPO3.Form:MultipleSelectCheckboxes':
            formBuilder:
              label: 'Multiple Select (Checkboxes)'
              group: select
              sorting: 140

          # group CUSTOM
          'TYPO3.Form:DatePicker':
            formBuilder:
              label: 'Date Picker'
              group: custom
              sorting: 100
              editors:
                validation:
                  availableValidators:
                    'TYPO3.FLOW3:DateTimeRange':
                      label: 'Date/Time Range'
                      viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.ValidatorEditor.MinimumMaximumValidatorEditor'
                      pathToMinimumOption: 'currentCollectionElement.options.earliestDate'
                      pathToMaximumOption: 'currentCollectionElement.options.latestDate'
          'TYPO3.Form:FileUpload':
            formBuilder:
              label: 'File Upload'
              group: custom
              sorting: 110
              editors:
                allowedExtensions:
                  sorting: 200
                  label: 'Allowed File Types'
                  propertyPath: 'properties.allowedExtensions'
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.SelectEditor'
                  availableElements:
                    0:
                      value: ['doc', 'docx', 'odt', 'pdf']
                      label: 'Documents (doc, docx, odt, pdf)'
                    1:
                      value: ['xls']
                      label: 'Spreadsheet documents (xls)'
          'TYPO3.Form:ImageUpload':
            formBuilder:
              label: 'Image Upload'
              group: custom
              sorting: 115

          'TYPO3.Form:StaticText':
            formBuilder:
              label: 'Static Text'
              group: custom
              sorting: 120
              editors:
                staticText:
                  sorting: 150
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.TextareaEditor'
                  label: 'Text'
                  propertyPath: 'properties.text'

          # group CONTAINER
          'TYPO3.Form:Section':
            formBuilder:
              label: 'Section (Fieldset)'
              group: container
              sorting: 100
              _isCompositeRenderable: true

          'TYPO3.Form:Page':
            formBuilder:
              label: 'Page'
              group: container
              sorting: 110
              _isTopLevel: true
              _isCompositeRenderable: true
              editors:
                identifier:
                  sorting: 110
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.IdentifierEditor'
                label:
                  label: 'Label'
                  propertyPath: 'label'
                  sorting: 120
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.TextEditor'

          'TYPO3.Form:PreviewPage':
            formBuilder:
              label: 'Preview Page'
              group: container
              sorting: 120
              _isTopLevel: true
              _isCompositeRenderable: false


          'TYPO3.Form:TextMixin':
            formBuilder:
              editors:
                placeholder:
                  sorting: 150
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.TextEditor'
                  label: 'Placeholder'
                  propertyPath: 'properties.placeholder'
                defaultValue:
                  sorting: 160
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.TextEditor'
                  label: 'Default Value'
                  propertyPath: 'defaultValue'
                validation:
                   availableValidators:
                    'TYPO3.FLOW3:Alphanumeric':
                      label: 'Alphanumeric'
                      sorting: 100
                    'TYPO3.FLOW3:Text':
                      label: 'Non-XML Text'
                      sorting: 110
                    'TYPO3.FLOW3:StringLength':
                      label: 'String Length'
                      sorting: 120
                      viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.ValidatorEditor.MinimumMaximumValidatorEditor'
                      required: false
                    'TYPO3.FLOW3:EmailAddress':
                      label: 'EMail'
                      sorting: 130
                      required: false

                    'TYPO3.FLOW3:Integer':
                      label: 'Integer Number'
                      sorting: 200
                    'TYPO3.FLOW3:Float':
                      label: 'Floating-point Number'
                      sorting: 210
                    'TYPO3.FLOW3:NumberRange':
                      label: 'Number Range'
                      sorting: 220
                      viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.ValidatorEditor.MinimumMaximumValidatorEditor'

                    'TYPO3.FLOW3:RegularExpression':
                      label: 'Regular Expression'
                      fieldLabel: 'Regular Expression'
                      fieldExplanationText: 'Enter a valid PHP PCRE Regular Expression here.'
                      sorting: 300
                      viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.ValidatorEditor.SimpleValueValidatorEditor'
                      pathToEditedValue: 'currentCollectionElement.options.regularExpression'

                    # Example of creating a custom "ZipCode" validator preset,
                    # which is defined in the "validatorPresets" above.
                    'TYPO3.FormBuilder:ZipCode':
                      label: 'Zip Code'
                      sorting: 140

          'TYPO3.Form:SelectionMixin':
            formBuilder:
              editors:
                options:
                  sorting: 200
                  viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.PropertyGrid'
                  # TODO: rename to "optionListPath"?
                  propertyPath: 'properties.options'
                  isSortable: true
                  enableAddRow: true
                  enableDeleteRow: true
                  columns:
                    0:
                      field: '_value'
                      name: 'Label'
                      editor: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.PropertyGrid.TextCellEditor'
                    1:
                      field: '_key'
                      name: 'Value'
                      editor: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.PropertyGrid.TextCellEditor'
          'TYPO3.Form:SingleSelectionMixin':
            formBuilder:
              editors:
                options:
                  shouldShowPreselectedValueColumn: 'single'
          'TYPO3.Form:MultiSelectionMixin':
            formBuilder:
              editors:
                options:
                  shouldShowPreselectedValueColumn: 'multiple'
                validation:
                  availableValidators:
                    'TYPO3.FLOW3:Count':
                      label: 'Number of submitted values'
                      sorting: 100
                      viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.ValidatorEditor.MinimumMaximumValidatorEditor'
